---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/convert":
    post:
      summary: Convert currency
      tags:
      - Conversions
      parameters: []
      responses:
        '201':
          description: Conversion successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: integer
                    example: 123
                  user_id:
                    type: integer
                    example: 1
                  from_currency:
                    type: string
                    example: USD
                  to_currency:
                    type: string
                    example: BRL
                  from_value:
                    type: number
                    example: 100.0
                  to_value:
                    type: number
                    example: 525.0
                  rate:
                    type: number
                    example: 5.25
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User not found
        '422':
          description: Invalid currency code
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid currency code
        '502':
          description: Exchange rate fetch failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Could not fetch exchange rate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 1
                from_currency:
                  type: string
                  example: USD
                to_currency:
                  type: string
                  example: BRL
                amount:
                  type: number
                  example: 100.0
              required:
              - user_id
              - from_currency
              - to_currency
              - amount
  "/transactions":
    get:
      summary: List transactions by user
      tags:
      - Transactions
      parameters:
      - name: user_id
        in: query
        required: true
        description: ID of the user
        schema:
          type: integer
      responses:
        '200':
          description: transactions listed
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    from_currency:
                      type: string
                    to_currency:
                      type: string
                    from_value:
                      type: number
                    to_value:
                      type: number
                    rate:
                      type: number
                  required:
                  - id
                  - user_id
                  - from_currency
                  - to_currency
                  - from_value
                  - to_value
                  - rate
                  - created_at
                  - updated_at
        '400':
          description: missing user_id parameter
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
